spring:
  profiles:
    active:
    - dev
---
server:
    port: 8001

mybatis:

  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.huxl.springcloud.entites  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
    profiles: dev
    application:
      name: microservicecloud-dept
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
      url: jdbc:mysql://localhost:3306/springclouddemo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8 # 数据库地址
      username: springcloud
      password: springcloud
      dbcp2:
        min-idle: 5                                    # 数据库连接池最小维持的连接数
        initial-size: 5                                # 初始化连接数
        max-total: 5                                   # 最大连接数
        max-wait-millis: 200                           # 等待连接获取最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservice-dept8001 #eureka 监控页面可以看到微服务名称端口
    prefer-ip-address: true # eureka 访问路径可以显示ip

info:
  app.name: microservicecloud
  company.name: h-com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
---

server:
    port: 8001

mybatis:

  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.huxl.springcloud.entites  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
    profiles: test
    application:
      name: microservicecloud-dept
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
      url: jdbc:mysql://localhost:3306/springclouddemo01?autoReconnect=true&useUnicode=true&characterEncoding=utf-8 # 数据库地址
      username: springcloud
      password: springcloud
      dbcp2:
        min-idle: 5                                    # 数据库连接池最小维持的连接数
        initial-size: 5                                # 初始化连接数
        max-total: 5                                   # 最大连接数
        max-wait-millis: 200                           # 等待连接获取最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: microservice-dept8001 #eureka 监控页面可以看到微服务名称端口
    prefer-ip-address: true # eureka 访问路径可以显示ip

info:
  app.name: microservicecloud
  company.name: h-com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
