spring:
  profiles:
    active:
    - dev
---
server: 
  port: 7001 
spring:
  profiles: dev
  application: 
    name: microservice-config-eureka-client

eureka: 
  instance:
    hostname: localhost
  client: 
    register-with-eureka: false
    fetch-registry: false   #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://localhost:7001/eureka/  
      #defaultZone: http://eureka-dev.com:7001/eureka/       
---

server: 
  port: 7001 
spring:
  profiles: dev
  application: 
    name: microservice-config-eureka-client

eureka: 
  instance:
    hostname: localhost
  client: 
    register-with-eureka: false
    fetch-registry: false   #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://localhost:7001/eureka/  
      #defaultZone: http://eureka-dev.com:7001/eureka/    